
logging:
  config: classpath:logback-spring.xml
spring:
  config:
    use-legacy-processing: true
  profiles:
    # jenkins 使用配置
#    active: ${spring.profiles.active}
    #本地环境
    active: dev
    #演示环境
#    active: centos-ys
    #生产环境
#    active: prod
  #中林环境
#    active: zlprod
# 版本
project:
  version: v1.0.39
  description:
    版本历史记录：                                                                                                                                                                            
     v1.0.2 2023.10.13:http://yirunscm.com:8080/issue/WMS-786; 启用spring boot3用于生产环境\n        
     v1.0.3 2023.10.13:http://yirunscm.com:8080/issue/WMS-787; 仓库数据权限授权报错问题<br>             
     v1.0.4 2023.10.13:http://yirunscm.com:8080/issue/WMS-790; 监管任务同步问题                    
     v1.0.5 2023.10.15:http://yirunscm.com:8080/issue/WMS-792;轨迹和验车接口调整，并启用版本号       
     v1.0.6 2023.10.16:;druid以及jdbc链接池配置升级，解决10秒超时，主要是要增加socketTimeout=0          
     v1.0.7 2023.10.18:;解决fastjson2堆栈移除问题。观察中。
     v1.0.8 2023.10.19:http://yirunscm.com:8080/issue/WMS-805/20231019增加接口判断监管任务的出库单是否已结算
     v1.0.9 2023.10.20:http://yirunscm.com:8080/issue/WMS-807;内容见yt
     v1.0.10 2023.10.21:http://yirunscm.com:8080/issue/WMS-815;内容见yt
     v1.0.11 2023.10.21:http://yirunscm.com:8080/issue/WMS-816;内容见yt
     v1.0.12 2023.10.27:http://yirunscm.com:8080/issue/WMS-821;内容见yt
     v1.0.13 2023.10.30:http://yirunscm.com:8080/issue/WMS-827;内容见yt
     v1.0.14 2023.11.1:http://yirunscm.com:8080/issue/WMS-831/;存货报表统计问题
     v1.0.15 2023.11.2:http://yirunscm.com:8080/issue/WMS-823/;生产订单(配方)、生产订单(配比)增加业务启动日期
     v1.0.16 2023.11.3:出库单提交校验bug
     v1.0.17 2023.11.8:物流订单选择入库计划&验车&轨迹日志查询
     v1.0.18 2023.11.8:问题紧急修复
     v1.0.19 2023.11.8:监管任务预警报错
     v1.0.20 2023.11.10:增加车牌颜色
     v1.0.21 2023.11.10:http://yirunscm.com:8080/issue/WMS-854;内容见详情
     v1.0.22 2023.11.17:监管任务查询报错，物流订单手动选择的入库计划，监管app点击卸货完成生成的入库单.单价需带出该入库单.订单编号.对应商品规格.合同单价；http://yirunscm.com:8080/issue/WMS-858/
     v1.0.23 2023.12.01:http://yirunscm.com:8080/issue/WMS-879/20231201-发版;内容见yt
     v1.0.24 2023.12.01:监管任务待审核预警，显示数据不对，不是卸货完成状态的也显示了，卸货完成未超过72小时的也显示了
     v1.0.25 2023.12.04:监管任务待审核预警，审核通过的数据未删除
     v1.0.27 2023.12.14:监管任务审核通过不可维护,作废
     v1.0.27 2023.12.14:生产订单作废问题
     v1.0.28 2023.12.14:生产订单作废报错
     v1.0.29 2023.12.19:出库计划中止接口过滤作废审核中的
     v1.0.30 2023.12.25:http://yirunscm.com:8080/issue/WMS-908/20231222
     v1.0.31 2024.1.8:新润航达发版
     v1.0.32 2024.1.12:http://yirunscm.com:8080/issue/WMS-925/2024112-中林发版
     v1.0.33 2024.1.15:新增调整单报错
     v1.0.34 2024.1.19:新润航达发版
     v1.0.35 2024.1.22:定时任务调整单日志问题
     v1.0.36 2024.1.22:定时任务配置删除连接池
     v1.0.37 2024.1.24:入库计划中止发版
     v1.0.38 2024.1.30:新增司机,车辆报错问题
     v1.0.39 2024.3.21:新每日库存逻辑,datachangelog
     v1.0.40 2024.5.23:1、生产计划功能；2、监管任务审核增加对应出入库单作废校验；3、监管任务详情，增加车辆情况照片显示；4、业务中台放货指令作废后，WMS对应出库计划状态更新优化；5、员工管理，若用户登录失败， 最后登录时间更新优化；6、监管任务，增加车辆情况照片。
     v1.0.41 2024.8.06:1.增加新增/修改/导出退货管理2.调整出库计划/出库单/报表管理3.调整监管任务退货信息